"""PM System — File-based project management with end-to-end pipeline.

Workflow:
  1. create_batch()        — create batch folder, save requirements.md
  2. run_spec_generation()  — requirement + architecture workflows → openspec docs
  3. prepare_tasks()        — parse tasks.md → create task folders (display only)
  4. run_batch_tdd()        — run single TDD pipeline for entire batch
  5. run_batch()            — orchestrate 1-4 serially
  6. resume_batch()         — resume if TDD not yet completed
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from toyshop.llm import LLM, create_llm
from toyshop.workflows.requirement import run_requirement_workflow
from toyshop.workflows.architecture import run_architecture_workflow
from toyshop.tdd_pipeline import run_tdd_pipeline, TDDResult


# =============================================================================
# Data classes
# =============================================================================

@dataclass
class TaskState:
    id: str
    title: str
    description: str
    status: str = "pending"  # pending | in_progress | completed | failed | skipped
    dependencies: list[str] = field(default_factory=list)
    assigned_module: str | None = None
    task_dir: Path | None = None


@dataclass
class BatchState:
    batch_id: str
    project_name: str
    batch_dir: Path
    status: str = "pending"  # pending | in_progress | completed | failed
    tasks: list[TaskState] = field(default_factory=list)
    error: str | None = None


# =============================================================================
# Helpers
# =============================================================================
def _slugify(text: str, max_len: int = 30) -> str:
    """Convert text to a filesystem-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return slug[:max_len]


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _save_progress(batch: BatchState) -> None:
    """Write progress.json for a batch."""
    completed = sum(1 for t in batch.tasks if t.status == "completed")
    failed = sum(1 for t in batch.tasks if t.status == "failed")
    current = next((t.id for t in batch.tasks if t.status == "in_progress"), None)
    _write_json(batch.batch_dir / "progress.json", {
        "batch_id": batch.batch_id,
        "project_name": batch.project_name,
        "status": batch.status,
        "total_tasks": len(batch.tasks),
        "completed_tasks": completed,
        "failed_tasks": failed,
        "current_task": current,
        "user_notes": "",
    })


def _save_task_json(task: TaskState) -> None:
    """Write task.json for a single task."""
    if task.task_dir is None:
        return
    data = {
        "id": task.id,
        "title": task.title,
        "description": task.description,
        "status": task.status,
        "dependencies": task.dependencies,
        "assigned_module": task.assigned_module,
    }
    _write_json(task.task_dir / "task.json", data)


# =============================================================================
# Task parsing
# =============================================================================

def parse_tasks_md(text: str) -> list[dict[str, Any]]:
    """Parse tasks.md into a list of task dicts.

    Supports multiple formats generated by the architecture workflow:

    Format A (openspec_bridge._tasks_to_markdown):
      ## 1. Top-level Title
      ### 1.1 Subtask Title
      **Dependencies:** 1.0, 1.1
      **Module:** parser

    Format B (render_tasks_markdown with emoji):
      ## ⬜ 1. Top-level Title
      - ⬜ **1.1** Subtask Title
        - Module: `parser`
        - Dependencies: 1.0, 1.1
    """
    tasks: list[dict[str, Any]] = []
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]

        # Format A: ## X. Title  or  ## ⬜ X. Title
        m_top = re.match(r"^##\s+(?:⬜\s+)?(\d+)\.\s+(.+)", line)
        # Format A: ### X.Y Title
        m_sub_h3 = re.match(r"^###\s+([\d.]+)\s+(.+)", line)
        # Format B: - ⬜ **X.Y** Title
        m_sub_bullet = re.match(r"^-\s+⬜\s+\*\*([\d.]+)\*\*\s+(.+)", line)

        # Format C: simple numbered list "1. Title"
        m_simple = re.match(r"^(\d+)\.\s+(.+)", line) if not m_top and not m_sub_h3 and not m_sub_bullet else None

        if m_top:
            task_id = m_top.group(1)
            title = m_top.group(2).strip()
            # Collect description until next heading or subtask
            desc_lines: list[str] = []
            i += 1
            while i < len(lines):
                ln = lines[i]
                if ln.startswith("## ") or ln.startswith("### ") or re.match(r"^-\s+⬜\s+\*\*", ln):
                    break
                if ln.strip() and not ln.strip().startswith("Format:"):
                    desc_lines.append(ln.strip())
                i += 1
            tasks.append({
                "id": task_id,
                "title": title,
                "description": "\n".join(desc_lines),
                "dependencies": [],
                "assigned_module": None,
            })

        elif m_sub_h3 or m_sub_bullet:
            m = m_sub_h3 or m_sub_bullet
            task_id = m.group(1)
            title = m.group(2).strip()
            desc_lines = []
            deps: list[str] = []
            module: str | None = None
            i += 1
            while i < len(lines):
                ln = lines[i]
                # Stop at next heading or next subtask bullet
                if ln.startswith("## ") or ln.startswith("### "):
                    break
                if re.match(r"^-\s+⬜\s+\*\*", ln):
                    break
                # Format A metadata
                dep_m = re.match(r"\s*\*\*Dependencies:\*\*\s*(.+)", ln)
                mod_m = re.match(r"\s*\*\*Module:\*\*\s*(.+)", ln)
                # Format B metadata: "  - Module: `name`"
                mod_b = re.match(r"\s+-\s+Module:\s*`?([^`]+)`?", ln)
                dep_b = re.match(r"\s+-\s+Dependencies:\s*(.+)", ln)
                if dep_m:
                    deps = [d.strip() for d in dep_m.group(1).split(",") if d.strip()]
                elif dep_b:
                    deps = [d.strip() for d in dep_b.group(1).split(",") if d.strip()]
                elif mod_m:
                    module = mod_m.group(1).strip().strip("`")
                elif mod_b:
                    module = mod_b.group(1).strip()
                elif ln.strip():
                    desc_lines.append(ln.strip())
                i += 1
            tasks.append({
                "id": task_id,
                "title": title,
                "description": "\n".join(desc_lines),
                "dependencies": deps,
                "assigned_module": module,
            })
        elif m_simple:
            task_id = m_simple.group(1)
            title = m_simple.group(2).strip()
            tasks.append({
                "id": task_id,
                "title": title,
                "description": "",
                "dependencies": [],
                "assigned_module": None,
            })
            i += 1
        else:
            i += 1

    return tasks


# =============================================================================
# Core functions
# =============================================================================

def create_batch(
    pm_root: str | Path,
    project_name: str,
    user_input: str,
) -> BatchState:
    """Create a new batch folder with requirements.md."""
    pm_root = Path(pm_root)
    pm_root.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    batch_id = f"{timestamp}_{_slugify(project_name)}"
    batch_dir = pm_root / batch_id
    batch_dir.mkdir(parents=True, exist_ok=True)

    # Save raw requirements
    (batch_dir / "requirements.md").write_text(
        f"# Requirements: {project_name}\n\n{user_input}\n",
        encoding="utf-8",
    )

    batch = BatchState(
        batch_id=batch_id,
        project_name=project_name,
        batch_dir=batch_dir,
        status="pending",
    )
    _save_progress(batch)
    print(f"[PM] Created batch: {batch_dir}")
    return batch


def run_spec_generation(batch: BatchState, llm: LLM) -> BatchState:
    """Run requirement + architecture workflows, save openspec docs."""
    print("[PM] Running spec generation (requirement → architecture)")
    batch.status = "in_progress"
    _save_progress(batch)

    openspec_dir = batch.batch_dir / "openspec"
    openspec_dir.mkdir(exist_ok=True)

    # Requirement workflow
    req_state = run_requirement_workflow(
        llm=llm,
        user_input=(batch.batch_dir / "requirements.md").read_text(encoding="utf-8"),
        project_name=batch.project_name,
    )
    if req_state.error or req_state.current_step != "done":
        batch.status = "failed"
        batch.error = f"Requirement workflow failed: {req_state.error}"
        _save_progress(batch)
        return batch

    if req_state.proposal_markdown:
        (openspec_dir / "proposal.md").write_text(req_state.proposal_markdown, encoding="utf-8")
        print(f"  Saved proposal.md")

    # Architecture workflow
    arch_state = run_architecture_workflow(llm=llm, proposal=req_state.proposal)
    if arch_state.error or arch_state.current_step != "done":
        batch.status = "failed"
        batch.error = f"Architecture workflow failed: {arch_state.error}"
        _save_progress(batch)
        return batch

    if arch_state.design_markdown:
        (openspec_dir / "design.md").write_text(arch_state.design_markdown, encoding="utf-8")
        print(f"  Saved design.md")
    if arch_state.tasks_markdown:
        (openspec_dir / "tasks.md").write_text(arch_state.tasks_markdown, encoding="utf-8")
        print(f"  Saved tasks.md")
    if arch_state.spec_markdown:
        (openspec_dir / "spec.md").write_text(arch_state.spec_markdown, encoding="utf-8")
        print(f"  Saved spec.md")

    _save_progress(batch)
    return batch


def prepare_tasks(batch: BatchState) -> list[TaskState]:
    """Parse tasks.md and create task folders."""
    tasks_md_path = batch.batch_dir / "openspec" / "tasks.md"
    if not tasks_md_path.exists():
        print("[PM] No tasks.md found")
        return []

    raw_tasks = parse_tasks_md(tasks_md_path.read_text(encoding="utf-8"))
    print(f"[PM] Parsed {len(raw_tasks)} tasks from tasks.md")

    tasks_root = batch.batch_dir / "tasks"
    tasks_root.mkdir(exist_ok=True)

    task_states: list[TaskState] = []
    for t in raw_tasks:
        slug = _slugify(t["title"])
        task_dir = tasks_root / f"{t['id']}_{slug}"
        task_dir.mkdir(exist_ok=True)

        ts = TaskState(
            id=t["id"],
            title=t["title"],
            description=t["description"],
            dependencies=t.get("dependencies", []),
            assigned_module=t.get("assigned_module"),
            task_dir=task_dir,
        )
        _save_task_json(ts)
        task_states.append(ts)

    batch.tasks = task_states
    _save_progress(batch)
    return task_states


def run_batch_tdd(batch: BatchState, llm: LLM) -> TDDResult:
    """Run a single TDD pipeline for the entire batch."""
    print("[PM] Running TDD pipeline for batch")
    batch.status = "in_progress"
    _save_progress(batch)

    # Workspace at batch level
    workspace = batch.batch_dir / "workspace"
    workspace.mkdir(exist_ok=True)
    ws_openspec = workspace / "openspec"
    if ws_openspec.exists():
        shutil.rmtree(ws_openspec)
    shutil.copytree(batch.batch_dir / "openspec", ws_openspec)

    # Agent logs at batch level
    log_dir = batch.batch_dir / "agent_logs"
    log_dir.mkdir(exist_ok=True)

    try:
        result = run_tdd_pipeline(
            workspace=workspace,
            llm=llm,
            log_dir=log_dir,
        )
    except Exception as e:
        batch.status = "failed"
        batch.error = f"TDD pipeline error: {e}"
        _save_progress(batch)
        _write_json(batch.batch_dir / "result.json", {"error": str(e)})
        return TDDResult(success=False, summary=str(e))

    # Save result
    _write_json(batch.batch_dir / "result.json", {
        "success": result.success,
        "whitebox_passed": result.whitebox_passed,
        "blackbox_passed": result.blackbox_passed,
        "retry_count": result.retry_count,
        "summary": result.summary,
        "files_created": result.files_created,
        "test_files": result.test_files,
    })

    batch.status = "completed" if result.success else "failed"
    if not result.success:
        batch.error = result.summary
    _save_progress(batch)

    status_icon = "✓" if result.success else "✗"
    print(f"  [{status_icon}] Batch TDD — {batch.status}")
    return result


def run_batch(
    pm_root: str | Path,
    project_name: str,
    user_input: str,
    llm: LLM | None = None,
) -> BatchState:
    """End-to-end: create batch → generate specs → parse tasks → run TDD pipeline."""
    if llm is None:
        llm = create_llm()

    # Step 1: Create batch
    batch = create_batch(pm_root, project_name, user_input)

    # Step 2: Generate openspec docs
    batch = run_spec_generation(batch, llm)
    if batch.status == "failed":
        return batch

    # Step 3: Parse tasks (for display/tracking only)
    prepare_tasks(batch)

    # Step 4: Run single TDD pipeline for entire batch
    result = run_batch_tdd(batch, llm)

    completed = sum(1 for t in batch.tasks if t.status == "completed")
    print(f"[PM] Batch finished: {batch.status} (TDD {'passed' if result.success else 'failed'}, "
          f"{len(batch.tasks)} tasks tracked)")
    return batch


def load_batch(batch_dir: str | Path) -> BatchState:
    """Load a BatchState from an existing batch directory."""
    batch_dir = Path(batch_dir)
    progress = _read_json(batch_dir / "progress.json")

    batch = BatchState(
        batch_id=progress["batch_id"],
        project_name=progress["project_name"],
        batch_dir=batch_dir,
        status=progress.get("status", "pending"),
    )

    # Reload tasks from task.json files
    tasks_root = batch_dir / "tasks"
    if tasks_root.exists():
        task_dirs = sorted(tasks_root.iterdir())
        for td in task_dirs:
            if not td.is_dir():
                continue
            tj = td / "task.json"
            if not tj.exists():
                continue
            data = _read_json(tj)
            batch.tasks.append(TaskState(
                id=data["id"],
                title=data["title"],
                description=data.get("description", ""),
                status=data["status"],
                dependencies=data.get("dependencies", []),
                assigned_module=data.get("assigned_module"),
                task_dir=td,
            ))

    return batch


def resume_batch(
    batch_dir: str | Path,
    llm: LLM | None = None,
) -> BatchState:
    """Resume a batch — re-run TDD if not yet completed."""
    if llm is None:
        llm = create_llm()

    batch = load_batch(batch_dir)

    if batch.status == "completed":
        print(f"[PM] Batch {batch.batch_id} already completed")
        return batch

    print(f"[PM] Resuming batch {batch.batch_id}")

    result = run_batch_tdd(batch, llm)
    print(f"[PM] Resume finished: {batch.status} (TDD {'passed' if result.success else 'failed'})")
    return batch
